version: "3.8"

services:
 
# STREAMLIT
  data-streamlit:
    build:
      context: .
    volumes:
      - ./data:/app
    tty: true
    ports:
      # HTTP
      - target: 8501
        published: 8501
        protocol: tcp